/* Auto-generated by genmsg_cpp for file /home/viki/catkin_ws/src/wifi_tools/msg/WifiData.msg */
#ifndef WIFI_TOOLS_MESSAGE_WIFIDATA_H
#define WIFI_TOOLS_MESSAGE_WIFIDATA_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "wifi_tools/AccessPoint.h"

namespace wifi_tools
{
template <class ContainerAllocator>
struct WifiData_ {
  typedef WifiData_<ContainerAllocator> Type;

  WifiData_()
  : header()
  , data()
  {
  }

  WifiData_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , data(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::vector< ::wifi_tools::AccessPoint_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::wifi_tools::AccessPoint_<ContainerAllocator> >::other >  _data_type;
  std::vector< ::wifi_tools::AccessPoint_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::wifi_tools::AccessPoint_<ContainerAllocator> >::other >  data;


  typedef boost::shared_ptr< ::wifi_tools::WifiData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wifi_tools::WifiData_<ContainerAllocator>  const> ConstPtr;
}; // struct WifiData
typedef  ::wifi_tools::WifiData_<std::allocator<void> > WifiData;

typedef boost::shared_ptr< ::wifi_tools::WifiData> WifiDataPtr;
typedef boost::shared_ptr< ::wifi_tools::WifiData const> WifiDataConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::wifi_tools::WifiData_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::wifi_tools::WifiData_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace wifi_tools

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::wifi_tools::WifiData_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::wifi_tools::WifiData_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::wifi_tools::WifiData_<ContainerAllocator> > {
  static const char* value() 
  {
    return "e1957fecb2a1644dd1be38d5c3a730a4";
  }

  static const char* value(const  ::wifi_tools::WifiData_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xe1957fecb2a1644dULL;
  static const uint64_t static_value2 = 0xd1be38d5c3a730a4ULL;
};

template<class ContainerAllocator>
struct DataType< ::wifi_tools::WifiData_<ContainerAllocator> > {
  static const char* value() 
  {
    return "wifi_tools/WifiData";
  }

  static const char* value(const  ::wifi_tools::WifiData_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::wifi_tools::WifiData_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header       # timestamp\n\
AccessPoint[] data  # wifi data of all access points\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: wifi_tools/AccessPoint\n\
string mac_address # MAC address of an access point\n\
int16 ss           # signal strength [RSSI]\n\
int16 noise        # noise\n\
\n\
";
  }

  static const char* value(const  ::wifi_tools::WifiData_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::wifi_tools::WifiData_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::wifi_tools::WifiData_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::wifi_tools::WifiData_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.data);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct WifiData_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wifi_tools::WifiData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::wifi_tools::WifiData_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::wifi_tools::AccessPoint_<ContainerAllocator> >::stream(s, indent + "    ", v.data[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // WIFI_TOOLS_MESSAGE_WIFIDATA_H

